### PR TITLE
Added programmatic interface to senpai's true feelings

### PR DESCRIPTION
**Pull request by zkat**

### CODE REVIEW

**Comment by johana-star** [comment]
Nice! I like separating all of that into a different file. I don't know that `index.js` fully captures the intent, but @kmanion I recommend you merge this.

**Comment by kmanion** [comment]
Thanks for this, @zkat. Merged.

**Comment by zkat** [comment]
the reason for `index.js` is so it'll be the default module when you
`require('senpai')` -- the same way `server.js` is what executes when you
`$ npm start`

On Tue, Oct 13, 2015, 18:07 Kiera Manion-Fischer notifications@github.com
wrote:

> Thanks for this, @zkat https://github.com/zkat. Merged.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kmanion/senpai/pull/3#issuecomment-147878856.
> 
> ## 

kat

**Comment by johana-star** [comment]
Ah, I see. So when someone installs a module with npm, they get access to that module's index.js as a default. Your strange conventions are making some sense. :)

**Comment by zkat** [comment]
Yes. Alternately, you can set the `main` field in your `package.json` to the module you want to be the default, if you don't wanna use `index.js` :)

**Pull request merged**
